### ISSUE TITLE
Portfolio Review for Greg

### ISSUE THREAD

**Issue by philmein23** [gregmagdsick/portfolio#20]
I really like the simplistic layout of the portfolio. Nicely done.

All the scripting code are refactored well and functional programming included when needed. 

My commentary or critiques from here on out are just for design purposes-

-One suggestion is to move your entire content to the center of the page since it's just a small container. This move will make your layout look more symmetrical and pleasing to the eye. 

Also, perhaps adding another media query for mobile phones (340 -480 px).

-Make your name header MUCH bigger. I think you would want that to stand out more when other users look at your portfolio, they will see your name as a grabber. 

-Your color scheme (white/grey) is good but maybe try to play around with other color schemes to add some flare to your page. Maybe a header banner (something that would represent your persona) would be a nice addition as well.

**Comment by philmein23** [comment]
-Increase the line-height of your about me section for readability. 
-Perhaps increase the font size as well (?).

**Comment by gregmagdsick** [comment]
-I did move the entire content to be centered on the page
-I also added a background image to better define me as a person (bringing in my affinity for photography)
-I didn't add a mobile phone media query because it didn't seem to need one as I changed window widths.
-I increased the text size of my header, my name
-In addition, I changed the main font color and played with a few options for hover colors, but ended up keeping it the same.
-Also, I did increase the line height of my bio to make it more readable
-Finally, I changed the behavior of my side nav bar (social links) to look nicer as the page width changes.
